### PR TITLE
Fix - Cursor pointer and Add - Hover effect

### LINKED ISSUE #34: [Enhancement] Make cursor pointer while hovering over products
**Description** 
Cursor is not changing to pointer and being default while hovering over the products and categories.
It is a bad user experience as user will not understand if these are clickable or not.

**Screenshot**
Screenshot (1637)

I would like to get assigned this issue so that I can work on it as soon as possible.

### PR DESCRIPTION
**Pull request by muhafiz5814**
Fixes #34 

**Description**
I have updated the styling of the products and categories component.
Now cursor is styled as `pointer` instead of `arrow` while hovering over the product or category.

Additionally I also updated the hovering effect on the product and category card to make it more user friendly by applying transform and transition properties.
Made the text on card clickable and underline while hover.

**Video**

https://github.com/user-attachments/assets/f6117b02-3a07-48d8-857b-dce6bfed6a65

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @muhafiz5814! 🎊 Thank you so much for taking the time to point this out.

**Comment by MinavKaria** [comment]
If you liked contributing to this project, don't forget to star the repository.

**Comment by muhafiz5814** [comment]
Hey @MinavKaria, Happy to contribute to your project.
Can you please add label `gssoc-ext`, `hactoberfest-accepted` and appropriate level so that it can be considered in participation.
Thank you.

**Comment by muhafiz5814** [comment]
> Hey @MinavKaria, Happy to contribute to your project. Can you please add label `gssoc-ext`, `hactoberfest-accepted` and appropriate level (I suggest 2 or 3) so that it can be considered in participation. Thank you.

Hey @MinavKaria, I would like to get your attention here. Please add the lebels.

**Pull request merged**
