### PR TITLE
"Add ML-Based Recommendations for Related Products Based on User Selections"

### PR DESCRIPTION
**Pull request by Renukanarayan**
**Description:**

This PR transforms the search feature by implementing ML-based recommendations. Previously, search results only displayed items that matched the beginning letters of the query. Now, with ML integration, search results suggest related products based on user selection, item type, and category, creating a more personalized experience.

**Highlights**
Enhanced Search: Upgrades search from exact matches to ML-driven recommendations.
Relevant Suggestions: Provides related products to improve user engagement and discovery.
 gssoc-ext, hacktoberfest-accepted, Level 3
**Issue Reference:** #137 opened by @Renukanarayan

pic1
pic2

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @Renukanarayan! 🎊 Thank you so much for taking the time to point this out.

**Comment by Renukanarayan** [comment]
This PR transforms the search feature by implementing ML-based recommendations. Previously, search results only displayed items that matched the beginning letters of the query. Now, with ML integration, search results suggest related products based on user selection, item type, and category, creating a more personalized experience.

**Comment by Renukanarayan** [comment]
How to run the recommendation search engine:
1.Navigate to recommendation_service
2.install needed libraries
Command:- pip install Flask flask-cors pandas scikit-learn
3. Run the file
Command:- python recommendation_service.py

**Comment by MinavKaria** [comment]
@Renukanarayan  I'll review the code soon and let you know in few days

**Comment by Renukanarayan** [comment]
@Minav karia     Don't I have chance to be on leaderboard

**Comment by Renukanarayan** [comment]
As a part of GSSOC i have done my contribution.Could you confirm that am i eligible for certification

**Comment by MinavKaria** [comment]
@Renukanarayan Sorry Contributor, We aren't using the python backend as of now, Thank you for your contribution. Feel free to open a new issue if you find any.

**Comment by Renukanarayan** [comment]
As of until,you used python right can I know what key changes made and other languages you get involved with

**Comment by MinavKaria** [comment]
@Renukanarayan Hey contributor , currently the whole project is working on MERN stack , I'll contact you if we'll need any help in python development.

**Comment by Renukanarayan** [comment]
Ok, thanks for the update.

**Pull request closed without merging**
