### PR TITLE
Tooltip for User Location with Beautiful Pop-up Design on the hover action

### PR DESCRIPTION
**Pull request by c2gup**
Updated the user location tooltip to create a more visually appealing pop-up effect on hover.
The tooltip now appears as a floating box over the userArea when hovered, displaying the full user location and pincode.

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @c2gup! 🎊 Thank you so much for taking the time to point this out.

**Comment by MinavKaria** [comment]
Are you a GSSOC or Hacktoberfest Contributor ?

**Comment by c2gup** [comment]
> Are you a GSSOC or Hacktoberfest Contributor ?
 
I am **GSSOC** contributor

**Comment by MinavKaria** [comment]
Thank you for contributing. If you liked the repository, don't forget to give a star.

**Comment by c2gup** [comment]
I already star the repo

**Pull request merged**
