### PR TITLE
solved #160 Added cursor animations

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
solved #160 
Added cursor animations
If possible kindly add levell3 label

https://github.com/user-attachments/assets/9f1e0c74-d189-439b-92a5-561d00d9c3ec

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @KapuluruBhuvaneswariVspdbct! 🎊 Thank you so much for taking the time to point this out.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir,if possible please add level3 label

**Comment by MinavKaria** [comment]
> sir,if possible please add level3 label

I'll merge your PR, after you remove changes from package-lock.json and only push the required changes

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
opened new pr #169

**Pull request closed without merging**
