### PR TITLE
PDF Invoice Generation for Purchased Items

### PR DESCRIPTION
**Pull request by ParasY1724**
**Issue No:** #70 

**Description:**
- Implementation of pdf-lib for PDF Generation
- Added WaterMark for PDF

**New Package Installed **
- pdf-lib
`npm i pdf -lib` install on client
**Result:**

https://github.com/user-attachments/assets/dac83053-51a8-40de-a4fd-7c61eb79145c

# Please Add gssoc-ext and level2 label

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @ParasY1724! 🎊 Thank you so much for taking the time to point this out.

**Review by MinavKaria — APPROVED** [review]

**Comment by MinavKaria** [comment]
Thank you for your Contribution. Don't forget to star if you like contributing the repository.

**Comment by MinavKaria** [comment]
@ParasY1724 Did this pull request update in GSSOC or Hacktoberfest ? Other contributor is having a problem with this

**Comment by ParasY1724** [comment]
> @ParasY1724 Did this pull request update in GSSOC or Hacktoberfest ? Other contributor is having a problem with this 

Nope my leaderboard in gssoc doesn't include this PR.I tried contacting Mentors.

**Comment by MinavKaria** [comment]
@sanjay-kv Please look into this

**Pull request merged**
