### PR TITLE
Fixes : #65 Updated Readme!

### PR DESCRIPTION
**Pull request by AskitEndo**
I have worked on #65 , and the contributors graph is fixed now!

@MinavKaria Do look onto it

### CODE REVIEW

**Review by MinavKaria — APPROVED** [review]

**Comment by MinavKaria** [comment]
@AskitEndo Did this pull request update in GSSOC or Hacktoberfest ? Other contributor is having a problem with this

**Comment by AskitEndo** [comment]
> @AskitEndo Did this pull request update in GSSOC or Hacktoberfest ? Other contributor is having a problem with this

None of my changes were on that Regard
You can Verify.

**Comment by MinavKaria** [comment]
What ?

**Comment by AskitEndo** [comment]
> What ? 
yes it does show

**Comment by AskitEndo** [comment]
> > What ? 
> yes it does show 
> 
> 
> 
@MinavKaria  this and only this shows in hacktober, and not in GSSOC

**Comment by MinavKaria** [comment]
@AskitEndo and in GSSOC ?

**Comment by AskitEndo** [comment]
> @AskitEndo and in GSSOC ?

Not it GSSOC, even in Hacktober not the previous one, only this

**Comment by MinavKaria** [comment]
@AskitEndo My Repo is hacktoberfest accepted through GSSOC, maybe there is issue from GSSOC side

**Comment by AskitEndo** [comment]
> @AskitEndo My Repo is hacktoberfest accepted through GSSOC, maybe there is issue from GSSOC side 

Haan, Even I think so

**Pull request merged**
