### PR TITLE
Add Geolocation Feature to Capture User's Location on Visit

### PR DESCRIPTION
**Pull request by OmkeshwarGupta**
Added a geolocation feature on  e-commerce website to capture the user's location when they visit the site. The location data will be used to enhance the user experience, such as displaying location-based recommendations, default shipping addresses, and pincode.

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @OmkeshwarGupta! 🎊 Thank you so much for taking the time to point this out.

**Comment by MinavKaria** [comment]
Hey @OmkeshwarGupta  can you change the `API_KEY` part to process.env.PINCODE_API_KEY

**Comment by OmkeshwarGupta** [comment]
I added the process.env.PINCODE_API_KEY  at the place of API_KEY and also add a console.log after fetching.

**Comment by MinavKaria** [comment]
@OmkeshwarGupta Last requirement , while fetching the pincode pls add a loading part, then I'll merge your request immediately

**Review by MinavKaria — APPROVED** [review]

**Pull request merged**
