### PR TITLE
Fixes : #12 The Sign In and Sign up buttons were swapped now Fixed

### PR DESCRIPTION
**Pull request by AskitEndo**
Clear the Issue on #12 where the Sign In and Sign Up Headings were swapped

### CODE REVIEW

**Comment by AskitEndo** [comment]
@MinavKaria Fixed the issue ,please do review over

**Comment by MinavKaria** [comment]
This change needed only 1 line change, why is there changes in more than 200 lines ?

**Comment by AskitEndo** [comment]
> This change needed only 1 line change, why is there changes in more than 200 lines ?

 @MinavKaria Prettier Extension made the code lines to adjust, I have Just made a little swap on Pages/Signup.jsx

**Comment by MinavKaria** [comment]
I'll close this PR , Send other PR without applying prettier

**Comment by AskitEndo** [comment]
> I'll close this PR , Send other PR without applying prettier, Is that ok ?

Okay, Let's do that way

**Comment by MinavKaria** [comment]
I noticed it now, You weren't assigned to that issue, I wont take your PR right now.

**Pull request closed without merging**
