### PR TITLE
Featuer : SuperSaver Item slider component added

### PR DESCRIPTION
**Pull request by Ashwinib26**
Previously the item cards in "**SuperSaver section**" appeared all together at a time , I have updated it by adding a **slider component** to the card items , where only three cards appear at a time and keeps on changing **cyclically** in fixed time intervals **continuously.**

After changes : 

https://github.com/user-attachments/assets/5e62f7c8-f73d-497c-ab19-3bbab50def9f

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @Ashwinib26! 🎊 Thank you so much for taking the time to point this out.

**Comment by Ashwinib26** [comment]
@MinavKaria , I have completed the assigned task , kindly review.
Thank  you !!

**Comment by MinavKaria** [comment]
@Ashwinib26 hey contributor ,can you please decrease the gap and make it centre aligned?

**Comment by Ashwinib26** [comment]
Yes Sure , @MinavKaria 
I will do it shortly.

**Comment by Ashwinib26** [comment]
I have made the required changes , @MinavKaria.

Kindly review.

**After changes :** 

https://github.com/user-attachments/assets/e88c144c-be6f-4068-a7c8-57f179679975

**Comment by MinavKaria** [comment]
@Ashwinib26 Sorry Contributor, I feel it is not looking good as per requirement

**Pull request closed without merging**
