### PR TITLE
ESLint Integration and Error Resolution

### PR DESCRIPTION
**Pull request by samar12-rad**
**Description:**
This PR introduces ESLint into the project to enhance code quality and maintainability. It includes the following changes:

- **ESLint Configuration:** Added a comprehensive ESLint configuration file to enforce coding standards across the codebase.
- **Error Resolution:** Fixed all identified linting errors, including issues related to code style, prop validation, and other best practices.
- **Code Quality Improvement:** Ensured consistent code formatting and reduced potential bugs by adhering to established coding standards.

**Impact:**
- Improved code readability and maintainability.
- Enhanced collaboration by standardizing code style across the project.

**Next Steps:**
- Review the ESLint rules and configurations to ensure they align with the team's preferences.
- Monitor for any new linting errors as development continues.

**Related Issues:**
- [Issue #74 ] @MinavKaria 

Thank you for reviewing this PR!

### CODE REVIEW

**Comment by samar12-rad** [comment]
There were total 34 files which had multiple erros in each of those. 
Those errors were resolved manually and 
The site was got proper inspection for its working. 


Further Improvements:
From now on, on one can push unused data in the repo

**Comment by samar12-rad** [comment]
Work done! on top priority

**Comment by MinavKaria** [comment]
@samar12-rad It may take some time to merge your PR

**Comment by samar12-rad** [comment]
What is the issue @MinavKaria ?

**Comment by samar12-rad** [comment]
I will resolve branch conflicts.

**Comment by MinavKaria** [comment]
Please try not break any feature 
@samar12-rad

**Comment by samar12-rad** [comment]
Ok

**Comment by MinavKaria** [comment]
@samar12-rad Hey resolve the conflict in the weekends, bcoz I'll need to review the code as changes are too much. I'll give level3 to this as there too many eslint issues resolved

**Comment by samar12-rad** [comment]
You are right. There are too many conflicts, I'll do it on weekend.

**Comment by MinavKaria** [comment]
@samar12-rad You are good to resolve the conflicts now.

**Comment by MinavKaria** [comment]
Currently this PR is not needed, When needed, I'll message you. Sorry for inconvenience. Feel free to open new issues,. @samar12-rad

**Pull request closed without merging**
