### PR TITLE
SEO enhancement for the website

### LINKED ISSUE #193: Generate Sitemap.xml and Robots.txt to improve SEO and Site Crawling
Adding sitemap.xml and robots.txt files helps optimize a website for search engines.

Sitemap.xml provides a list of important URLs, helping search engines discover, crawl, and index new and updated content faster, improving SEO.

Robots.txt controls which parts of the site search engines can access, preventing indexing of sensitive or unimportant pages, conserving crawl budget, and reducing server load.

Together, they enhance site visibility, performance, and search engine ranking.

ASSIGN WITH LEVEL 2 OR LEVEL 3

### PR DESCRIPTION
**Pull request by amiya-cyber**
fixes #193 
close #193 

please assign and add level to this pr

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @amiya-cyber! 🎊 Thank you so much for taking the time to point this out.

**Comment by amiya-cyber** [comment]
Hello @MinavKaria can you review the pr

**Comment by amiya-cyber** [comment]
Hello @MinavKaria can you merge the pr asap please give level 3

**Comment by MinavKaria** [comment]
@amiya-cyber I can give level 2 at max

**Comment by amiya-cyber** [comment]
Ok but please merge the pr

**Review by MinavKaria — APPROVED** [review]

**Comment by MinavKaria** [comment]
@amiya-cyber Don't forget to star the repository, if you liked contributing to this repository.

**Pull request merged**
