### PR TITLE
Enhance Product Selection Interface for Improved User Experience

### PR DESCRIPTION
**Pull request by AdityaP700**
This pull request from issue #28  focuses on optimizing the product selection interface to create a more customer-friendly experience. Key changes include:

- Rearrangement of Increment and Decrement Operators: The placement of these buttons has been modified to better align with user behavior, as studies suggest that users are more inclined to add products rather than remove them.
image

- Improved Button Spacing: Increased spacing between the increment/decrement buttons and the product quantity for better visual clarity and usability.
image

- Responsive Icon Behavior: Added hover effects for the icons, enhancing their responsiveness and providing visual feedback to users when they interact with them.

### CODE REVIEW

**Review by MinavKaria — COMMENTED** [review]
Welcome to Our repository, @AdityaP700! 🎊 Thank you so much for taking the time to point this out.

**Comment by AdityaP700** [comment]
Hello @MinavKaria ,Apologies for the delay caused . I would appreciate it if you could take a moment to review the changes I have made. Please let me know if you have any suggestions or require further modifications. Thanks in anticipation :)

**Comment by MinavKaria** [comment]
@AdityaP700 I cannot see any changes except the footer icons

**Comment by AdityaP700** [comment]
@MinavKaria ,As mentioned in issue #28, my task was to fix the icon alignment. Previously, the alignment looked like this
image
After making adjustments, it now looks like this:
image
Well if any additional comments/suggestions you want to provide then do let me know . Awaiting for your response.

**Pull request closed without merging**
