### PR TITLE
Bug Fixed 👍🏻 . Go Back Button Working Now !!

### LINKED ISSUE #87: [Bug] Go back option for User Not handled properly
I want to work on this bug to ensure the functionality of the button. 
image

@MinavKaria Please Assign me this issue.

### PR DESCRIPTION
**Pull request by Akshithsaai**
Fixes #87 
I have fixed the go back button which closes the dialog. (expected behaviour) 

Please check and merge ASAP @MinavKaria . 
Also I would Like to contribute more. Please assign me to any other issue .

### CODE REVIEW

**Comment by Akshithsaai** [comment]
@MinavKaria I have Fixed the Go back Button .

**Comment by MinavKaria** [comment]
@Akshithsaai please send a basic video or picture to show your changes

**Comment by Akshithsaai** [comment]
https://github.com/user-attachments/assets/126ab2cd-49f3-46c4-b419-1b439ea719fd

@MinavKaria

**Comment by MinavKaria** [comment]
@Akshithsaai Remove all the changes from package-lock.json and only push the required changes

**Comment by Akshithsaai** [comment]
package-lock.json should be ignored by .git-ignore @MinavKaria .

**Comment by Akshithsaai** [comment]
Should I undo changes in lock file and commit again @MinavKaria ?

**Comment by Akshithsaai** [comment]
@MinavKaria This PR is not merged.

**Comment by MinavKaria** [comment]
I'll merge it today, I have noted it down

**Comment by Akshithsaai** [comment]
> I'll merge it today, I have noted it down

Ok @MinavKaria.
I would like to contribute more, Can you assign me another issue if possible.

**Comment by MinavKaria** [comment]
First, Only commit those lines which you have changed, don't commit the package and package-lock.json

**Comment by MinavKaria** [comment]
> Should I undo changes in lock file and commit again @MinavKaria ?

Yes

**Pull request merged**
